### ISSUE TITLE
Missing version number when running `docker-credential-gcr version`

### ISSUE THREAD

**Issue by obourgain** [GoogleCloudPlatform/docker-credential-gcr#155]
I just updated the binary to 2.1.19 and running 
`docker-credential-gcr version`
prints
```
❯ docker-credential-gcr version
Google Container Registry Docker credential helper (devel)
```

while the previous version I had printed an actual version number
```
❯ docker-credential-gcr version
Google Container Registry Docker credential helper 2.1.0
```

**Comment by rafibarash** [comment]
Can you install via the go cli like so?

```shell
go install github.com/GoogleCloudPlatform/docker-credential-gcr/v2@latest
```

This isn't reproducible when installed with the above command

```shell
~
❯ rm ~/go/bin/docker-credential-gcr

~
❯ which docker-credential-gcr
docker-credential-gcr not found

~
❯ go install github.com/GoogleCloudPlatform/docker-credential-gcr/v2@latest

~
❯ which docker-credential-gcr
/Users/rbarash/go/bin/docker-credential-gcr

~
❯ docker-credential-gcr version
Google Container Registry Docker credential helper 2.1.25
```

I'll update the documentation with this installation instruction, it is a bit out of date and uses `go get`

**Comment by obourgain** [comment]
yes, installing with `go install` prints the version `2.1.25`, while the binary downloaded from the Github release assets print `devel`

**Comment by dsiebel** [comment]
I created a [PR to address this](#176), maybe one of the maintainers could have a look
FYI @yihanzhen, @MeBaranov, ?
