### ISSUE TITLE
v2.1.23 Release contains no pre-built assets

### ISSUE THREAD

**Issue by StevenACoffman** [GoogleCloudPlatform/docker-credential-gcr#165]
The most recent release https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/tag/v2.1.23 does not contain the pre-built assets that have accompanied all prior releases.

I have a [github action setup-docker-credential-gcr)](https://github.com/StevenACoffman/setup-docker-credential-gcr) that will download and install these pre-built assets, and it is currently failing for the latest.

In the action, I can work around this by pinning the version to the prior release but I would rather re-use the official prebuilt assets of the latest release.

**Comment by alteredego** [comment]
This invalidates things like the instructions found here -
https://cloud.google.com/artifact-registry/docs/docker/authentication#standalone-helper

**Comment by psalaberria002** [comment]
Also hitting this. Can someone build and upload the binaries?

**Comment by StevenACoffman** [comment]
Hey, for those following this issue who use GCP, please open a GCP support issue in order to get this work prioritized.

**Comment by rafibarash** [comment]
Hm, looks like the [go release job](https://github.com/GoogleCloudPlatform/docker-credential-gcr/actions/runs/10065542841/job/27824896147) failed. Will debug

**Comment by rafibarash** [comment]
Looks like there's one more issue, hopefully will be fixed this time

**Comment by rafibarash** [comment]
Fixed on [v2.1.25](https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/tag/v2.1.25) 😄
