### ISSUE TITLE
WARNING! Using --password via the CLI is insecure. Use --password-stdin.

### ISSUE THREAD

**Issue by ensonic** [GoogleCloudPlatform/docker-credential-gcr#17]
It looks like docker changed the commandline option.
```
> gcloud --project xxx -- tag image eu.gcr.io/project/image:<ver>
ERROR: Docker CLI operation failed:

WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error saving credentials: error storing credentials - err: exit status 1, out: `docker-credential-gcr/helper: this operation is unsupported for GCR, please see docker-credential-gcr documentation for supported login methods. 'gcloud docker' is unnecessary when using docker-credential-gcr, use 'docker' instead.`

ERROR: (gcloud.docker) Docker login failed.

> docker --version
Docker version 17.09.0-ce, build afdb6d4
```

**Comment by KingEmet** [comment]
We made a change to `gcloud docker` to simplify some of the hacks used to determine which behavior to adopt when invoking `docker login`. Since you have `docker-credential-gcr` configured, you can use the naked `docker` commands.

**Comment by ensonic** [comment]
I am not sure why you propose what the error message already states. We're using a build system and this called it that way, so the change that needs to be done is to change it there. The above example is just what worked before and got silently broken.
