### ISSUE TITLE
Build docker-credential-gcr go binary statically

### ISSUE THREAD

**Issue by priyawadhwa** [GoogleCloudPlatform/docker-credential-gcr#31]
It would be really useful to be able to build docker-credential-gcr as a static binary to run in scratch images. 
If it's just a matter of adding the flag to the Makefile, I could submit a PR for it! 

@dlorenc

**Comment by dlorenc** [comment]
Thanks, Jake. You are a gentleman and a scholar.

**Comment by dekkagaijin** [comment]
You know it
![mmmmmmhmmmmmm](https://media.giphy.com/media/bQOptcTAfcs36/giphy.gif)
