### ISSUE TITLE
command not found: docker-credential-gcr

### ISSUE THREAD

**Issue by steveoh** [GoogleCloudPlatform/docker-credential-gcr#50]
> gcloud components install docker-credential-gcr

Your current Cloud SDK version is: 210.0.0
Installing components from version: 210.0.0

┌──────────────────────────────────────────────────────────────────────────┐
│                   These components will be installed.                    │
├──────────────────────────────────────────────────────┬─────────┬─────────┤
│                         Name                         │ Version │   Size  │
├──────────────────────────────────────────────────────┼─────────┼─────────┤
│ Google Container Registry's Docker credential helper │         │         │
│ Google Container Registry's Docker credential helper │   1.5.0 │ 1.8 MiB │
└──────────────────────────────────────────────────────┴─────────┴─────────┘

For the latest full release notes, please visit:
  https://cloud.google.com/sdk/release_notes

Do you want to continue (Y/n)?  Y

╔════════════════════════════════════════════════════════════╗
╠═ Creating update staging area                             ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Installing: Google Container Registry's Docker creden... ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Installing: Google Container Registry's Docker creden... ═╣
╠════════════════════════════════════════════════════════════╣
╠═ Creating backup and activating new installation          ═╣
╚════════════════════════════════════════════════════════════╝

Performing post processing steps...done.

Update done!

$ docker-credential-gcr configure-docker
zsh: command not found: docker-credential-gcr

$ which gcloud
/usr/local/bin/gcloud

$ gcloud --version
Google Cloud SDK 210.0.0
bq 2.0.34
core 2018.07.27
docker-credential-gcr
gsutil 4.33

What am I missing?

**Comment by dekkagaijin** [comment]
Did you install `gcloud` in the same session? You might have to restart your terminal before gcloud's component bin directory gets included on your system PATH

**Comment by steveoh** [comment]
I installed gcloud with brew and then tried to install this cli. Restarted session etc and its still not on path.

**Comment by dekkagaijin** [comment]
Ah, yeah, the Homebrew package is an unsupported community effort.

I'd try removing the brew version and using the supported installation: https://cloud.google.com/sdk/docs/quickstart-macos

**Comment by steveoh** [comment]
thanks! That worked.

I'll open an issue in the brew repo since that was the problem. Or how the gcloud cli installed the docker-credential-gcr after the brew install.

I can open a new issue but I'm not confused. I have a few containers in the gcr.

I ran docker-credential-gcr configure-docker, docker-credential-gcr gcr-login

I then deleted my k8s deployment and recreated it. But I still get permission issues. This worked when the gcr was public but we want to keep it private. Are there some specific steps I'm missing or permissions I need to add to allow k8s to pull on my behalf?

**Comment by dekkagaijin** [comment]
Are you using GKE? If so, you'll need to make sure that the nodes' service account has the `Storage Object Viewer` role in the project where your images are hosted, and that its configured with Storage reader scopes when the cluster is created (both the service account and the scopes can be seen in the advanced options during cluster creation in the cloud console).

Otherwise, you'll have to give your cluster ImagePullSecrets: http://docs.heptio.com/content/private-registries/pr-gcr.html
