### ISSUE TITLE
"gcloud auth configure-docker" overwrites existing credHelpers key

### ISSUE THREAD

**Issue by dionjwa** [GoogleCloudPlatform/docker-credential-gcr#52]
I had a `~/.docker/config.json` file with existing entries in the `credHelpers` key, but running ```gcloud auth configure-docker``` wiped those and replaced them with the `gcloud` entries.

So it would be great to check the presence of a `credHelpers` key and merge.

**Comment by dekkagaijin** [comment]
This repo is specifically for `docker-credential-gcr`, the standalone helper. Please use `gcloud feedback` to send feedback about `gcloud auth configure-docker`
