### ISSUE TITLE
SHA256 checksums don't match binary releases

### ISSUE THREAD

**Issue by pgm** [GoogleCloudPlatform/docker-credential-gcr#59]
Hello,

I tried downloading the binaries but was alerted that the checksums do not match what was listed on the release page.

For example if I execute:
curl -fsSL https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v1.5.0/docker-credential-gcr_linux_amd64-1.5.0.tar.gz | openssl dgst -sha256

I get the SHA256:
ca8f0baa185b779162830986fbe7192ff15efebc0dba8153b0a9bce1100ca4ed

However, on the release page it reports the SHA256 as: 
linux-amd64
1ca0b551fb36322c479c08f264e616cc693d4045531586a38b106192016b43ee

Are the sha's correct (or am I doing something wrong, perhaps using the wrong digest?)

Thanks

**Comment by dekkagaijin** [comment]
The digests are for the binaries themselves, not the archives.

**Comment by pgm** [comment]
Ah, gotcha - thanks for clarifying

**Comment by bseib** [comment]
Shucks, I got stung by this too, where the checksums did not match the file I downloaded. I tried several times, trying to figure out what was wrong, then I finally decided to file a bug report, and then discovered this closed issue.

In general, isn't it more common to provide checksums for the artifact being downloaded? I would suggest showing those checksums instead.

I expected these checksums:

```
3307a19706608c02298521db9858ae0fbd639db2c4c288690b34b9729b9cb24a  docker-credential-gcr_darwin_386-1.5.0.tar.gz
1dbfb1e643817ee9ef6f8d241600d73a5a5661587e8618461e619637ec37ec9d  docker-credential-gcr_darwin_amd64-1.5.0.tar.gz
43ce91635ccbe3acb47b16136793c3093cbeb4aef8fe3021f2e1063f1aa98a64  docker-credential-gcr_linux_386-1.5.0.tar.gz
ca8f0baa185b779162830986fbe7192ff15efebc0dba8153b0a9bce1100ca4ed  docker-credential-gcr_linux_amd64-1.5.0.tar.gz
7c711f240221fe5fddd63df56cc54db6610f774a23beb3dada729774194773b3  docker-credential-gcr_windows_386-1.5.0.tar.gz
69d421ba37f0480a9bbd1758b17056579c4242c1745d4234b5731e219fbbad59  docker-credential-gcr_windows_386-1.5.0.zip
5af8cc169bedc7a054fcce21f2bf46824d54c8cf0923c3fd18b06c7d5076b210  docker-credential-gcr_windows_amd64-1.5.0.tar.gz
45229c153fa288cd4a223d806b005f419ef8128333baf08dad3358dc94313531  docker-credential-gcr_windows_amd64-1.5.0.zip
```
