### ISSUE TITLE
Feature Request: Provide an apt package for docker-credential-gcr

### ISSUE THREAD

**Issue by gzimmers** [GoogleCloudPlatform/docker-credential-gcr#71]
Currently we have to do a manual install of the gcloud SDK on GCP ubuntu VMS because gcloud is installed via apt, but provides no way of installing docker-credential-gcr without ripping out the whole install and reinstalling manually.

It seems odd that this is the one package omitted from apt compared to all of the other packages. It's also pretty painful to do all of that just to allow pulling of docker images from GCR on google produced images. I'm hoping there is either planned support for an apt docker-credential-gcr package sometime soon in the future, or some other solution without having to reinstall the sdk.

I'm open to ideas, and while I know we can produce an image with our manual reinstall, we are required to repave our machines every 30-90 days and don't have a good "image CI/CD" process in place to deal with something like this in time for production.

Thanks for taking the time to read this,
Cheers

**Comment by jonjohnsonjr** [comment]
This might be naive, but can you just use gcloud as a credential helper?

```
gcloud auth configure-docker
```

**Comment by gzimmers** [comment]
This worked after upgrading to the most recent google-cloud-sdk version!

Thanks,
Cheers
