### ISSUE TITLE
GKE serviceaccounts using workload identity auth frequently timeout

### ISSUE THREAD

**Issue by AdamMichaelLong** [GoogleCloudPlatform/docker-credential-gcr#75]
GKE serviceaccounts using workload identity auth frequently timeout when gke metadata server is under load. 

see pull request: https://github.com/GoogleCloudPlatform/docker-credential-gcr/pull/72

and upstream fix https://github.com/googleapis/google-cloud-go/commit/fbf2f5121ef6008eb9b7e5c67aa0c9abfa7ac7fc

```
 error getting credentials - err: exit status 1, out: `docker-credential-gcr/helper: could not retrieve GCR's access token: Get http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform: net/http: timeout awaiting response headers
```

**Comment by dekkagaijin** [comment]
I've created a PR which updated the library to HEAD: https://github.com/GoogleCloudPlatform/docker-credential-gcr/pull/76

**Comment by dekkagaijin** [comment]
https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/tag/v2.0.1
