### ISSUE TITLE
No release artifacts for v2.0.5?

### ISSUE THREAD

**Issue by jdolitsky** [GoogleCloudPlatform/docker-credential-gcr#93]
Are release artifacts available for v2.0.5?

404 Not Found for https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v2.0.5/docker-credential-gcr_linux_amd64-2.0.5.tar.gz

**Comment by jonjohnsonjr** [comment]
@rafibarash

**Comment by rafibarash** [comment]
My mistake! I'll add them by tomorrow afternoon

**Comment by rafibarash** [comment]
You should be able to download the artifact from that link now.

FYI - here's a snippet I just added to the release notes:
> **Note**: This release is a little busted in that I didn't update the config PatchVersion from 4 -> 5. Sometime in the next couple weeks I'll automate out this config const so we don't run into this issue again.
